name: Build and Release Electron App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      # 安装依赖
      - name: Install dependencies
        run: npm ci

      # 构建前端资源和 Electron 应用
      - name: Build application
        run: npm run build

      # 打包应用
      - name: Package application
        run: npm run build:win

      # 上传构建产物到 GitHub Actions artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-app
          path: release/

      # 压缩 dist/mitm/ 为 mitm.zip
      - name: Create zip archive
        run: |
          Compress-Archive -Path dist/* -DestinationPath wxdown.zip
        shell: pwsh

      # 上传打包结果
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable-zip
          path: wxdown.zip
          retention-days: 7
